version: '3'
services:
  postgres:
    image: postgres:13.3
    container_name: PostgreSQL
    ports:
      - "5432:5432"
    volumes:
      - ./data/posgres:/var/lib/postgresql/data/pgdata
      - ./bd-dump:./data/dump
    environment:
        POSTGRES_PASSWORD: school
        PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  redis:
    image: redis:7.0.2
    container_name: redis
    restart: always

  app:
     build:
       context:.
       dockerfile: ./ops-tools/docker/image/app/Dockerfile
     container_name: application
     ports:
       - "8888:8888"
     environment:
       REDIS_PORT=6379
       POSTGRES_PORT=5432
       POSTGRES_HOST: postgres
       REDIS_HOST: redis
     restart: always
     links:
       - postgres
       - redis


